version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  grafana:
    image: "grafana/grafana:latest"
    links:
      - "redis:redis"
      - "leaderboard:leaderboard"
    ports:
      - "3000:3000"
    environment:
        - GF_INSTALL_PLUGINS=redis-datasource,grafana-simple-json-datasource
  leaderboard:
    image: "maguec/grafanaleaderboard:latest"
    depends_on:
      - redis
      - grafana
    ports:
      - "5000:5000"
